language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24.3"
  - "5.16"
  # "5.10"

env:
  # NEO4J_VER=3.5.0
  - NEO4J_VER=3.4.10
  - NEO4J_VER=3.3.9
  - NEO4J_VER=3.2.13
  # NEO4J_VER=3.1.9
  # NEO4J_VER=3.0.12
  - NEO4J_VER=2.3.12

jdk: oraclejdk8

install:
  - curl -O https://dist.neo4j.org/neo4j-community-$NEO4J_VER-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VER-unix.tar.gz
  - neo4j-community-$NEO4J_VER/bin/neo4j start
  - cpanm -nq Dist::Zilla
  - dzil authordeps --missing | cpanm -nq
  - dzil listdeps --missing --author | cpanm -nq

before_script:
  - neo4j-community-$NEO4J_VER/bin/neo4j status
  - curl -u neo4j:neo4j -d '{"password":"xkcd792"}' -X POST -H 'Content-Type:application/json' http://localhost:7474/user/neo4j/password
  - export TEST_NEO4J_PASSWORD=xkcd792
  # export AUTHOR_TESTING=1

script:
  # prove t
  - dzil test

