name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "41 0 8,23 * *"  # twice a month

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.38
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --missing --author | cpanm -nq
      - name: Run unit tests
        run: dzil test
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
          NO_NETWORK_TESTING: 1
      - name: Build
        run: dzil build --no-tgz --in build_dir
      - uses: actions/upload-artifact@v3
        with:
          name: build_dir
          path: build_dir
          retention-days: 1

  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    name: "Perl ${{ matrix.perl }} / Neo4j ${{ matrix.neo4j }}"
    strategy:
      fail-fast: true
      matrix:
        include:
          - neo4j: "5.10.0"  # Neo4j 5
            perl: "5.38"
          - neo4j: "4.4.23"  # Neo4j 4
            perl: "5.36"
          #- neo4j: "4.2.4"   # Neo4j 4, old-style Jolt
          #  perl: "5.32"
          #- neo4j: "4.0.11"  # Neo4j 4, without Jolt
          #  perl: "5.30"
          - neo4j: "3.5.35"  # Neo4j 3
            perl: "5.26"
          - neo4j: "2.3.12"  # Neo4j 2
            perl: "5.16"
    env:
      TEST_NEO4J_PASSWORD: xkcd_792
    steps:

      - name: Install Neo4j
        uses: johannessen/actions-install-neo4j@v1
        with:
          neo4j-version: ${{ matrix.neo4j }}
          password: ${{ env.TEST_NEO4J_PASSWORD }}
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules: ExtUtils::MakeMaker~6.78
          enable-modules-cache: false
      - name: Get distribution
        uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: .
      - name: Install distribution dependencies
        run: cpanm -nq --installdeps --with-develop .
      - name: Version info
        run: |
          curl -s http://localhost:7474/ -u "neo4j:$TEST_NEO4J_PASSWORD" | grep neo4j_version || true
          curl -s http://localhost:7474/db/data/ -u "neo4j:$TEST_NEO4J_PASSWORD" | grep neo4j_version || true
          ls | grep --max-count=1 neo4j-community || true
          which perl
          perl -V

      - name: Test
        run: |
          perl -Ilib -MNeo4j::Driver -e "print Neo4j::Driver->new->basic_auth(neo4j=>'$TEST_NEO4J_PASSWORD')->session->run(\"RETURN 'Connected to Neo4j\\n'\")->single->get;" || echo "Error testing Neo4j connection"
          prove -lr t xt
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
