name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "41 0 8,23 * *"  # twice a month

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.36
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --missing --author | cpanm -nq
      - name: Run unit tests
        run: dzil test
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
          NO_NETWORK_TESTING: 1
      - name: Build
        run: dzil build --no-tgz --in build_dir
      - uses: actions/upload-artifact@v2
        with:
          name: build_dir
          path: build_dir
          retention-days: 1

  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    name: "Perl ${{ matrix.perl }} / Neo4j ${{ matrix.neo4j }}"
    strategy:
      fail-fast: true
      matrix:
        include:
          - neo4j: "5.3.0"   # Neo4j 5
            perl: "5.36"
          - neo4j: "4.4.15"  # Neo4j 4
            perl: "5.34"
          #- neo4j: "4.2.4"   # Neo4j 4, old-style Jolt
          #  perl: "5.32"
          #- neo4j: "4.0.11"  # Neo4j 4, without Jolt
          #  perl: "5.30"
          - neo4j: "3.5.35"  # Neo4j 3
            perl: "5.26"
          - neo4j: "2.3.12"  # Neo4j 2
            perl: "5.16"
    env:
      TEST_NEO4J_PASSWORD: xkcd_792
      NEO4J_DISTS: "https://dist.neo4j.org"
      NEO4J: ${{ matrix.neo4j }}
    steps:

      - name: Install Neo4j 5
        if: ${{ startsWith( matrix.neo4j , '5.') }}
        run: |
          curl -sLO https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jre_x64_linux_hotspot_17.0.5_8.tar.gz
          tar -xzf ibm-semeru-open-jre_x64_linux_17.0.5_8_openj9-0.35.0.tar.gz
          export JAVA_HOME=jdk-17.0.5+8-jre
          eval "${JAVA_HOME:-/usr}/bin/java -version"
          curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
          tar -xzf neo4j-community-$NEO4J-unix.tar.gz
          neo4j-community-$NEO4J/bin/neo4j-admin dbms set-initial-password "$TEST_NEO4J_PASSWORD" || echo "Password change using neo4j-admin failed."
          neo4j-community-$NEO4J/bin/neo4j start
          perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep Started neo4j-community-$NEO4J/logs/neo4j.log > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
          cat neo4j-community-$NEO4J/logs/neo4j.log
          neo4j-community-$NEO4J/bin/neo4j status

      - name: Install Neo4j 4
        if: ${{ startsWith( matrix.neo4j , '4.') }}
        run: |
          curl -sLO https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jre_x64_linux_hotspot_11.0.17_8.tar.gz
          tar -xzf OpenJDK11U-jre_x64_linux_hotspot_11.0.17_8.tar.gz
          export JAVA_HOME=jdk-11.0.17+8-jre
          eval "${JAVA_HOME:-/usr}/bin/java -version"
          curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
          tar -xzf neo4j-community-$NEO4J-unix.tar.gz
          neo4j-community-$NEO4J/bin/neo4j-admin set-initial-password "$TEST_NEO4J_PASSWORD" || echo "Password change using neo4j-admin failed."
          neo4j-community-$NEO4J/bin/neo4j start
          perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep Started neo4j-community-$NEO4J/logs/neo4j.log > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
          cat neo4j-community-$NEO4J/logs/neo4j.log
          neo4j-community-$NEO4J/bin/neo4j status

      - name: Install Neo4j 2/3
        if: ${{ startsWith( matrix.neo4j , '3.') || startsWith( matrix.neo4j , '2.') }}
        run: |
          curl -sLO https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jre_x64_linux_hotspot_8u352b08.tar.gz
          tar -xzf OpenJDK8U-jre_x64_linux_hotspot_8u352b08.tar.gz
          export JAVA_HOME="`pwd`/jdk8u352-b08-jre"
          eval "${JAVA_HOME:-/usr}/bin/java -version"
          curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
          tar -xzf neo4j-community-$NEO4J-unix.tar.gz
          neo4j-community-$NEO4J/bin/neo4j-admin set-initial-password "$TEST_NEO4J_PASSWORD" || echo "Password change using neo4j-admin failed."
          NEO4J_LOG=logs/neo4j.log
          if [ "$NEO4J" = "2.3.12" ] ; then neo4j-community-$NEO4J/bin/neo4j start-no-wait ; NEO4J_LOG=data/log/console.log ; else neo4j-community-$NEO4J/bin/neo4j start ; fi
          perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep 'Started\\\|interface ready' neo4j-community-$NEO4J/$NEO4J_LOG > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
          sleep 1
          curl -u neo4j:neo4j -fid "{\"password\":\"$TEST_NEO4J_PASSWORD\"}" -H "Content-Type:application/json" -s http://localhost:7474/user/neo4j/password || echo "Password change using cURL failed."
          cat neo4j-community-$NEO4J/$NEO4J_LOG
          neo4j-community-$NEO4J/bin/neo4j status

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Get distribution
        uses: actions/download-artifact@v2
        with:
          name: build_dir
          path: .
      - name: Install distribution dependencies
        run: cpanm -nq --installdeps --with-develop .
      - name: Version info
        run: |
          curl -s http://localhost:7474/ -u "neo4j:$TEST_NEO4J_PASSWORD" | grep neo4j_version || true
          curl -s http://localhost:7474/db/data/ -u "neo4j:$TEST_NEO4J_PASSWORD" | grep neo4j_version || true
          ls | grep --max-count=1 neo4j-community || true
          which perl
          perl -V

      - name: Test
        run: |
          perl -Ilib -MNeo4j::Driver -e "print Neo4j::Driver->new->basic_auth(neo4j=>'$TEST_NEO4J_PASSWORD')->session->run(\"RETURN 'Connected to Neo4j\\n'\")->single->get;" || echo "Error testing Neo4j connection"
          prove -lr t xt
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
