name: Run cpan-distros.t

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9].[0-9]+"
  schedule:
    - cron: "41 0 15 * *"  # once a month, on the 15th

jobs:
  cpan-distros:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.34
    env:
      TEST_NEO4J_PASSWORD: xkcd_792
    steps:
      - name: Install Neo4j 4
        run: |
          curl -sLO https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.11_9.tar.gz
          tar -xzf OpenJDK11U-jre_x64_linux_hotspot_11.0.11_9.tar.gz
          export JAVA_HOME=jdk-11.0.11+9-jre
          eval "${JAVA_HOME:-/usr}/bin/java -version"
          curl -sLO $NEO4J_DISTS/neo4j-community-$NEO4J-unix.tar.gz
          tar -xzf neo4j-community-$NEO4J-unix.tar.gz
          neo4j-community-$NEO4J/bin/neo4j-admin set-initial-password "$TEST_NEO4J_PASSWORD" || echo "Password change using neo4j-admin failed."
          neo4j-community-$NEO4J/bin/neo4j start
          perl -E "print'Waiting for server to be ready ...';for(0..60){last if 0+\`grep Started neo4j-community-$NEO4J/logs/neo4j.log > /dev/null 2>&1 && echo 1 || echo 0\`;print'.';sleep 1}say' OK.'"
          cat neo4j-community-$NEO4J/logs/neo4j.log
          neo4j-community-$NEO4J/bin/neo4j status
        env:
          NEO4J: "4.3.10"
          NEO4J_DISTS: "https://dist.neo4j.org"

      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Neo4j::Driver dependencies
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --missing --author | cpanm -nq
      - name: Install Neo4j::Driver
        run: |
          dzil install
      - name: Install Neo4j::Driver dependants
        run: |
          cpanm REST::Neo4p
      - name: Setup database for testing
        run: |
          perl -MNeo4j::Driver -e 'Neo4j::Driver->new->basic_auth(neo4j=>$ENV{TEST_NEO4J_PASSWORD})->session->run($ENV{TEST_DATA_CREATE});'
        env:
          TEST_DATA_CREATE: "CREATE (neo4j :Server { name: 'Neo4j' })
          CREATE (lib  :Library { name: 'libneo4j-client' })
          CREATE (alien   :Dist { name: 'Neo4j::Client' })
          CREATE (bolt    :Dist { name: 'Neo4j::Bolt' })
          CREATE (driver  :Dist { name: 'Neo4j::Driver' })
          CREATE (neo4p   :Dist { name: 'REST::Neo4p' })
          CREATE (dbd     :Dist { name: 'DBD::Neo4p' })
          CREATE (dbd)-[:USES]->(neo4p)-[:USES]->(driver)
          CREATE (driver)-[pp:USES]->(neo4j)
          CREATE (driver)-[xs:USES]->(bolt)
          CREATE (bolt)-[:USES]->(alien)-[:USES]->(lib)-[:USES]->(neo4j)
          SET pp.protocols = ['HTTP Jolt', 'HTTP JSON']
          SET bolt.XS = true
          SET driver.XS = false"
      - name: Test
        run: |
          dzil run 'prove -v xt/author/cpan-distros.t'
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
